#include<stdio.h>

int main()
{
    char str[20] = "HELLO I AM THOUFIK" ;
    for(int i = 0 ; str[i] != '\0';i++)
    {
        printf("STRING VALUE:%c\n",str[i]);
        printf("INTERGER VALUE:%d\n",str[i]);
        printf("ASCII VALUE:%x\n",str[i]);
    }
}

/*STRING VALUE:H
INTERGER VALUE:72
ASCII VALUE:48
STRING VALUE:E
INTERGER VALUE:69
ASCII VALUE:45
STRING VALUE:L
INTERGER VALUE:76
ASCII VALUE:4c
STRING VALUE:L
INTERGER VALUE:76
ASCII VALUE:4c
STRING VALUE:O
INTERGER VALUE:79
ASCII VALUE:4f
STRING VALUE: 
INTERGER VALUE:32
ASCII VALUE:20
STRING VALUE:I
INTERGER VALUE:73
ASCII VALUE:49
STRING VALUE: 
INTERGER VALUE:32
ASCII VALUE:20
STRING VALUE:A
INTERGER VALUE:65
ASCII VALUE:41
STRING VALUE:M
INTERGER VALUE:77
ASCII VALUE:4d
STRING VALUE: 
INTERGER VALUE:32
ASCII VALUE:20
STRING VALUE:T
INTERGER VALUE:84
ASCII VALUE:54
STRING VALUE:H
INTERGER VALUE:72
ASCII VALUE:48
STRING VALUE:O
INTERGER VALUE:79
ASCII VALUE:4f
STRING VALUE:U
INTERGER VALUE:85
ASCII VALUE:55
STRING VALUE:F
INTERGER VALUE:70
ASCII VALUE:46
STRING VALUE:I
INTERGER VALUE:73
ASCII VALUE:49
STRING VALUE:K
INTERGER VALUE:75
ASCII VALUE:4b*/