class NEW_PRODUCT_FOR_HOUSE:
    def PRODUCT_RATE(T):
        T.CAR_RATE = int(input("ENTER THE CAR RATE:"))
        T.FRIGH_RATE  =  int(input("ENTER THE FRIGH RATE:"))
        T.BIKE_RATE = int(input("ENTER THE BIKE RATE:"))
        T.AIR_CONDISNOR_RATE = int(input("ENTER THE A/C RATE:"))
        T.TV_RATE = int(input("ENTER THE TV RATE:"))

class TOTAL_PRODUCT_FOR_HOUSE(NEW_PRODUCT_FOR_HOUSE):
    def TOTAL_RATE_OF_PRODUCT(T):
        T.TOTAL_PRODUCT_RATE = T.CAR_RATE + T.FRIGH_RATE + T.BIKE_RATE + T.AIR_CONDISNOR_RATE + T.TV_RATE
        print("TOTAL PRODUCT FOR HOUSE AND RATE:",T.TOTAL_PRODUCT_RATE)


t2 = TOTAL_PRODUCT_FOR_HOUSE()
t2.PRODUCT_RATE()
t2.TOTAL_RATE_OF_PRODUCT()


